### ISSUE TITLE
Decrypting the configfile.bin

### ISSUE THREAD

**Issue by hbgoodman** [The5heepDev/FIOS-G1100#4]
I'm confused to how you decrypt the configfile.bin.   Any help would be appreciated.

**Comment by Brandonv101** [comment]
@hbgoodman I think there is a script posted in another issue thread that has instructions

**Comment by hbgoodman** [comment]
I was able to get the file decrypted however, I'm running into an issue enctypting the my updated file:  

I get the following error:

root@kali:~/Desktop/fios_config# python3 gwdecrypt.py configfile.json new.bin
Traceback (most recent call last):
  File "gwdecrypt.py", line 58, in <module>
    main()
  File "gwdecrypt.py", line 43, in main
    json_data = decrypt(data_in)
  File "gwdecrypt.py", line 26, in decrypt
    data_out = cipher.decrypt(data_in[32:])
  File "/usr/lib/python3/dist-packages/Crypto/Cipher/blockalgo.py", line 295, in decrypt
    return self._cipher.decrypt(ciphertext)
ValueError: Input strings must be a multiple of 16 in length

I've done a little research and it seems like it needs some kind of padding?  But isn't that what is happening in the def pad(s) function?

I'm not sure how to fix this.   

I'm using:
Python 3.6.6rc1 in Kali

**Comment by hbgoodman** [comment]
Never mind I think I fugured it out.
